#!/bin/sh -e

echo "Creating desktop entry..."
cat > /usr/share/applications/gtasa-savegame-editor.desktop <<EOF
    [Desktop Entry]
    Type=Application
    Encoding=UTF-8
    Name=GTA San Andreas Savegame Editor
    Comment=GTA San Andreas Savegame Editor
    Exec=java -jar /usr/share/gtasa-savegame-editor/lib/gtasa-savegame-editor.jar
    Icon=/usr/share/gtasa-savegame-editor/icon-256.png
    Terminal=false
EOF

echo "Creating shell shortcut..."
cat > /usr/bin/gtasa-savegame-editor <<EOF
    #!/bin/bash
    java -jar /usr/share/gtasa-savegame-editor/lib/gtasa-savegame-editor.jar
EOF
chmod +x /usr/bin/gtasa-savegame-editor
