#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule

# create desktop entry?
db_get gtasase/create_desktop_entry
if [ "$RET" = "true" ]; then
  echo "Removing desktop entry..."
  rm -f /usr/share/applications/gtasa-savegame-editor.desktop
fi


# create shell shortcut?
db_get gtasase/create_shell_shortcut
if [ "$RET" = "true" ]; then
  echo "Removing shell shortcut..."
  rm -f /usr/bin/gtasa-savegame-editor
fi
