name: Linux

on:
  release:
    types: [released, prereleased]

jobs:
  jar:
    name: 🐧 .jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Build jar
        run: mvn clean install -Dmaven.javadoc.skip=true -B -V
      - name: Package jar
        run: |
          mkdir deploy
          cp -v savegame-editor/target/*-jar-with-dependencies.jar deploy/
          zip -r "GTA:SA-Savegame-Editor.jar.zip" deploy/
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: GTA:SA-Savegame-Editor.jar.zip
  deb:
    name: 🐧 .deb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Build deb
        run: mvn clean install -Pdeb -Dmaven.javadoc.skip=true -B -V
      - name: Package deb
        run: |
          mkdir deploy
          cp -v savegame-editor/target/*.deb deploy/
          zip -r "GTA:SA-Savegame-Editor.deb.zip" deploy/
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: GTA:SA-Savegame-Editor.deb.zip
  rpm:
    name: 🐧 .rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Build rpm
        run: mvn clean install -Prpm -Dmaven.javadoc.skip=true -B -V
      - name: Package rpm
        run: |
          mkdir deploy
          cp -v savegame-editor/target/rpm/savegame-editor/RPMS/noarch/*.rpm deploy/
          zip -r "GTA:SA-Savegame-Editor.rpm.zip" deploy/
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: GTA:SA-Savegame-Editor.rpm.zip
