name: Windows

on:
  release:
    types: [released, prereleased]

jobs:
  exe:
    name: 🏢 .exe
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Install WiX Toolset
        run: |
          choco install wixtoolset --version=3.14.1 -y
          echo "C:\Program Files (x86)\WiX Toolset v3.14\bin" >> $env:GITHUB_PATH
      - name: Build exe
        run: mvn clean install -Pdeb "-Dmaven.javadoc.skip=true" -B -V -Pwindows
      - name: Package exe
        run: |
          mkdir deploy
          copy savegame-editor\target\*.exe deploy\
          Compress-Archive deploy GTA-SA-Savegame-Editor.Windows.zip
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: GTA-SA-Savegame-Editor.Windows.zip
